#!/usr/bin/env bash
# Install nginx on your web-01 server.
if [ ! -x /usr/sbin/nginx ]; then
  apt-get -y update
  apt-get -y install nginx
  echo 'Hello World!' > /var/www/html/index.html
  service nginx restart
else
  echo "Nginx already installed.."
fi
