#!/usr/bin/env bash
# Install nginx on your web-01 server.
if [ ! -x /usr/sbin/nginx ]; then
  apt-get -y update
  apt-get -y install nginx
  echo "Hello World!" > /var/www/html/index.nginx-debian.html
  service nginx start
else
  echo "Nginx already installed.."
  echo "Hello World!" > /var/www/html/index.nginx-debian.html
fi
