#!/usr/bin/env bash
# added a redirection..

redirect_me="location /redirect_me {\n return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; }"


if [ ! -x /usr/sbin/nginx ]; then
  apt-get -y update
  apt-get -y install nginx
  echo "Hello World!" > /var/www/html/index.nginx-debian.html
  sed -i "s.location / {.$redirect_me" /etc/nginx/sites-enabled/default
  service nginx start
else
  echo "Hello World!" > /var/www/html/index.nginx-debian.html
  sed -i "s|location / {|$redirect_me" /etc/nginx/sites-enabled/default
  service nginx restart
fi
