#!/usr/bin/env bash
# added a redirection..

# a multiline variable config..
redirect_me="\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"

#404-NotFoundErr
xyzfoo="\tlocation /xyzfoo {\n\t\treturn 404 \"Ceci n'est pas une page\n\";\n\t}"

if [ ! -x /usr/sbin/nginx ]; then
  apt-get -y update
  apt-get -y install nginx
  echo "Hello World!" > /var/www/html/index.nginx-debian.html
  sed -i "53i\\$redirect_me" /etc/nginx/sites-available/default
  sed -i "57i\\$xyzfoo" /etc/nginx/sites-available/default
  service nginx start
else
  echo "Hello World!" > /var/www/html/index.nginx-debian.html
  sed -i "53i\\$redirect_me" /etc/nginx/sites-available/default
  sed -i "57i\\$xyzfoo" /etc/nginx/sites-available/default
  service nginx restart
fi
