#!/usr/bin/env bash
# configures a new ubuntu machine.

host="\tadd_header X-Served-By $HOSTNAME;\n"
if [ ! -x /usr/sbin/nginx ]; then
  apt-get -y update
  apt-get -y install nginx
  sed -i "48i\\$host" /etc/nginx/sites-available/default
  service nginx start
else
  sed -i "48i\\$host" /etc/nginx/sites-available/default
  service nginx restart 
fi
