#!/usr/bin/env bash
# displays numbers from 1 to 20 with conditions
var=1
while [ "$var" -le 20 ]; do
	echo "$var"
	case "$var" in 4)
		echo "bad luck from China" ;;
	9)
		echo "bad luck from Japan" ;;
	17)
		echo "bad luck from Italy" ;;
	esac
	((var++))
done
